remote_theme: mmistakes/minimal-mistakes@3.4.1
plugins:
  - jekyll-remote-theme

title: "My Dark Fantasy Portfolio"
description: "Dark fantasy, Lovecraftian & absurd writing portfolio"

author:
  name: Your Name

dark_mode: true

header_pages:
  - index.md
  - sfw.md
  - nsfw.md
  - contact.md
